### ISSUE TITLE
Keep init-nodes as fallback if all nodes fail

### ISSUE THREAD

**Issue by zuiderkwast** [Ericsson/ered#56]
If all nodes change their IP addresses, the init node could be a hostname that resolves to the IP updated addresses. If we keep the init node address, we can use it as a fallback if we've lost connection to all nodes.

**Comment by drmull** [comment]
It used to work that way. Maybe you just need to revert this commit:
https://github.com/Ericsson/ered/commit/7d6c461f1fa2c4890e836145668206531218e291

**Comment by zuiderkwast** [comment]
Yeah, I know. I must have missed the reasoning for why it was done that way, but now I know.

I don't think we should keep the unused connection though, as we used to do.

When the init-nodes is a service name (a hostname that maps to multiple IP addresses, and updated whenever the node IPs change) then it makes sense to keep it around, but a user can also just use an IP of one of the nodes as the init node and later this IP is no longer part of the cluster. In the worst case, that node is later configured as part of another cluster, so CLUSTER SLOTS from this node returns something completely wrong. In this case it is not a good idea to keep it around and use it for slot mapping updates.

I want to use the init nodes just as a fallback when all nodes fail. It is more agnostic to how the cluster is deployed and used.

**Comment by drmull** [comment]
In the original design the initial nodes were preferred when sending an heartbeat with the intent of avoiding the situation where the client is connected to a cluster and a new cluster is formed using the configured address. If for some reason there are two active clusters I think the expected behavior is that the client is connected to the cluster containing the configured address, anything else would seem very odd to me! 
Maybe I am not getting the use case here. Is your example based on any real world scenario?

**Comment by zuiderkwast** [comment]
No user asked for it, if that's what you mean, but OTOH we don't have very many users.

A scenario is a rolling upgrade of the database nodes, while the application (where ered is running) is not stopped. The database nodes are replaced one by one. Afterwards, the init node is no longer part of the cluster. Later its IP may be reused for another microservice, application node or possibly database node of another cluster. The init nodes just that: a node to use for initializing the client, not a node that is always part of the cluster. It's hypothetical but not unrealistic in my understanding.

Another case where we have another preference for CLUSTER SLOTS: When we get a MOVED redirect, we want to send CLUSTER SLOTS to the node that returned the MOVED redirect, since we know that it's aware of the slot migration and it's typically the old owner of the slot. Not all other nodes maybe be aware of it yet.
